### ISSUE TITLE
Geometry.js refers to Face3 and SolidColorMaterial which do not exist.

### ISSUE THREAD

**Issue by raurir** [vorg/pex#13]
http://vorg.github.io/pex/docs/pex-geom/Geometry.html

face should be an array of vertices

material should be: var material = new materials.SolidColor();

Indeed this example isn't working at all it seems.

**Comment by vorg** [comment]
Fixed in https://github.com/vorg/pex-geom/commit/d69d057660e94188ddc6c9c2e2c37f70160b22f3

For a full working example please see here http://vorg.github.io/pex/examples/geom.Geometry/
