### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by joaodafonseca** [vorg/pex#15]
Got the following error after running  'sudo npm install -g pex' on the terminal, any idea why?
Thanks,

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pex/node_modules/exec-sync/node_modules/ffi
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "pex"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ffi@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@1.2.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

**Comment by vorg** [comment]
Can you tell me more about the os version, node version etc?

On Thu, Feb 12, 2015 at 2:06 PM, joaodafonseca <notifications@github.com>
wrote:

> Got the following error after running 'sudo npm install -g pex' on the
> terminal, any idea why?
> Thanks,
>
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.
> make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
> gyp ERR! build error
> gyp ERR! stack Error: make failed with exit code: 2
> gyp ERR! stack at ChildProcess.onExit
> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
> gyp ERR! stack at ChildProcess.emit (events.js:110:17)
> gyp ERR! stack at Process.ChildProcess._handle.onexit
> (child_process.js:1067:12)
> gyp ERR! System Darwin 14.0.0
> gyp ERR! command "node"
> "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
> "rebuild"
> gyp ERR! cwd
> /usr/local/lib/node_modules/pex/node_modules/exec-sync/node_modules/ffi
> gyp ERR! node -v v0.12.0
> gyp ERR! node-gyp -v v1.0.2
> gyp ERR! not ok
> npm ERR! Darwin 14.0.0
> npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "pex"
> npm ERR! node v0.12.0
> npm ERR! npm v2.5.1
> npm ERR! code ELIFECYCLE
>
> npm ERR! ffi@1.2.5 install: node-gyp rebuild
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ffi@1.2.5 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the ffi package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR! npm owner ls ffi
> npm ERR! There is likely additional logging output above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vorg/pex/issues/15>.
>



-- 
Marcin Ignac
http://marcinignac.com
@marcinignac

**Comment by joaodafonseca** [comment]
Hi thanks for the quick reply.

I'm on osx 10.10
- node v0.12.0
- npm 2.5.1

**Comment by vorg** [comment]
Updated few packages so they compile until 0.12 https://github.com/vorg/pex/commit/674e79ab4a534d34c02d1c4131fbd1b371db9adf and released 0.6.0. It should work now. Just install it again with:

`npm install pex -g`

**Comment by joaodafonseca** [comment]
Thanks Marcin works like a charm now
